charity/charity/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

from commons import views as common_views

urlpatterns = [
    path("accounts/login/", common_views.azure_ad_login, name='login'),
    path('accounts/login/callback/', common_views.azure_ad_callback, name='azure_ad_callback'),
    path('accounts/approve_waiting', common_views.user_is_not_approved, name='user_is_not_approved'),
    path("accounts/logout/", common_views.ad_logout, name='logout'),
    path('admin/', admin.site.urls),
    path('budgets/', include('budgets.urls')),
    path('comments/', include('comments.urls')),
    path('customfields/', include('customfields.urls')),
    path('files/', include('files.urls')),
    path('filters/', include('filters.urls')),
    path('funds/', include('funds.urls')),
    path('notifications/<uuid:id>/details/',
         common_views.view_notification_details, name='view_notification_details'),
    path('mailings/', include('mailings.urls')),
    path('processes/', include('processes.urls')),
    path('projects/', include('projects.urls')),
    path('submissions/', include('submissions.urls')),
    path('tasks/', include('tasks.urls')),
    path('wards/', include('wards.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

charity/files/urls.py
from django.urls import path

from . import views

app_name = "files"

urlpatterns = [
    path('<uuid:id>/', views.get_file, name='get_file'),
    path('content_types/<str:model>/items/<uuid:target_id>/attach/',
         views.attach_file, name='attach_file'),
    path('<uuid:id>/content_types/<str:model>/items/<uuid:target_id>/remove/',
         views.remove_file, name='remove_file'),
    path('<uuid:id>/content_types/<str:model>/items/<uuid:target_id>/change_access/', views.change_file_access, name='change_file_access')
]

charity/funds/urls.py
from django.urls import path

from . import views

app_name = "funds"

urlpatterns = [
    path('', views.get_list, name='get_list'),
    path('<uuid:id>/details/', views.get_details, name='get_details'),
    path('index/partial/', views.get_current_details_partial, name='get_current_details_partial'),
    path('index/',views.get_current_details, name='get_current_details'),
    path('index/volunteers/<uuid:id>/details/', views.get_volunteer_details, name='get_volunteer_details'),
    path('index/contributions/add/', views.add_contribution, name='add_contribution'),
    path('index/contributions/<uuid:id>/details/', views.get_contribution_details, name='get_contribution_details'),
    path('index/contributions/<uuid:id>/remove/', views.remove_contribution, name='remove_contribution'),
    path('index/volunteers/add/', views.add_volunteer, name='add_volunteer'),
    path('index/volunteers/<uuid:id>/edit/', views.edit_volunteer_profile, name='edit_volunteer_profile'),
    path('index/volunteers/<uuid:id>/cover/', views.add_volunteer_cover, name='add_volunteer_cover'),
    path('index/contributors/add/', views.add_contributor, name='add_contributor'),
    path('index/contributors/<uuid:id>/details/', views.get_contributor_details, name='get_contributor_details'),
    path('index/contributors/<uuid:id>/edit/', views.edit_contributor_details, name='edit_contributor_details')
]

charity/mailings/urls.py
from django.urls import path

from . import views

app_name = "mailings"

urlpatterns = [
    path('groups', views.get_gorups_list, name='get_gorups_list'),
    path('groups/add/', views.add_group, name='add_group'),
    path('groups/<uuid:id>/remove/', views.remove_group, name='remove_group'),
    path('groups/<uuid:id>/details/',
         views.get_group_details, name='get_group_details'),
    path('groups/<uuid:id>/edit/', views.edit_group, name='edit_details'),
    path('groups/<uuid:id>/recipients/add/',
         views.add_recipient, name='add_recipient'),
    path('groups/<uuid:id>/recipients/<uuid:recipient_id>/remove/',
         views.remove_recipient, name='remove_recipient'),
    path('templates/', views.get_templates_list, name='get_templates_list'),
    path('templates/add/', views.add_template, name='add_template'),
    path('templates/<uuid:id>/edit/', views.edit_template, name='edit_template'),
    path('templates/<uuid:id>/remove/', views.remove_template, name='remove_template'),
    path('content_fields', views.get_content_type_details,
         name='get_content_type_details')
]

charity/submissions/urls.py
from django.urls import path

from . import views

app_name = "submissions"

urlpatterns = [
    path('', views.get_list, name='get_list'),
    path('add/', views.add_submission, name='add_submission'),
    path('<uuid:id>/details/', views.get_submission_details, name='get_submission_details'),
    path('<uuid:id>/edit/', views.edit_submission, name='edit_submission'),
    path('<uuid:id>/remove/', views.remove_submission, name='remove_submission'),
    path('<uuid:id>/add_ward/', views.add_submission_ward, name='add_submission_ward'),
    path('<uuid:id>/wards/<uuid:ward_id>/remove', views.remove_submission_ward, name='remove_submission_ward'),
    path('<uuid:id>/send/', views.send_submission, name='send_submission')
]

charity/submissions/models.py
from django.contrib.auth.models import User
from django.db import models

from commons.models import Base
from funds.models import Fund
from mailings.models import MailingGroup, MailingTemplate
from wards.models import Ward


class SubmissionSentStatus(models.TextChoices):
    DRAFT = 'DRAFT', 'Is draft'
    SENT = 'SENT', 'Sent'
    IN_PROGRESS = 'IN_PROGRESS', 'In progress'
    PARTIALLY_SENT = 'PARTIALLY_SENT', 'Partially sent'


class Submission(Base):
    name = models.CharField(max_length=256, blank=False,
                            unique=True, null=False)
    notes = models.TextField(blank=True, null=True)
    is_draft = models.BooleanField(default=True, null=False)
    author = models.ForeignKey(User, on_delete=models.PROTECT)
    fund = models.ForeignKey(Fund, on_delete=models.PROTECT)
    wards = models.ManyToManyField(Ward)
    mailing_template = models.ForeignKey(
        MailingTemplate, on_delete=models.PROTECT, related_name='submissions')
    mailing_group = models.ForeignKey(MailingGroup, on_delete=models.PROTECT, related_name='submissions')
    status = models.CharField(
        choices=SubmissionSentStatus.choices, max_length=16)

charity/submissions/forms.py
from django import forms

from commons.mixins import FormControlMixin, InitialMixin
from mailings.models import MailingGroup, MailingTemplate

from .models import Submission, SubmissionSentStatus


class AddSubmissionForm(
        forms.ModelForm,
        FormControlMixin, InitialMixin):
    __initial__ = ['fund', 'author']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        InitialMixin.__init__(self)

        self.form.author.widget = forms.HiddenInput()
        self.form.fund.widget = forms.HiddenInput()
        self.form.mailing_group.queryset = MailingGroup.objects.filter(
            fund=self.fund)
        self.form.mailing_template.queryset = MailingTemplate.objects.filter(
            fund=self.fund)
        FormControlMixin.__init__(self)

    class Meta:
        model = Submission
        exclude = ['id', 'date_created', 'wards', 'is_draft', 'status']

    def save(self):
        if self.instance._state.adding:
            self.instance.is_draft = True
            self.instance.status = SubmissionSentStatus.DRAFT

        return super().save(True)

charity/submissions/views.py
from django.core.paginator import Paginator
from django.contrib.auth.decorators import user_passes_test
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from django.views.decorators.http import require_http_methods, require_GET, require_POST

from commons import DEFAULT_PAGE_SIZE
from commons.exceptions import ApplicationError
from commons.functional import user_should_be_volunteer, render_generic_form

from wards.forms import AttachWardToTargetForm

from .forms import AddSubmissionForm
from .models import Submission
from .requirements import submission_can_be_edited
from .tasks import send_submssions


@user_passes_test(user_should_be_volunteer)
@require_GET
def get_list(request):
    paginator = Paginator(
        Submission.objects
        .select_related('mailing_template', 'mailing_group', 'author__volunteer_profile').filter(
            fund=request.user.fund), DEFAULT_PAGE_SIZE)
    return render(request, 'submissions_list.html', {
        'title': 'Submissions',
        'items_count': paginator.count,
        'page': paginator.get_page(request.GET.get('page')),
    })


@user_passes_test(user_should_be_volunteer)
@require_http_methods(['GET', 'POST'])
def add_submission(request):
    return render_generic_form(request, form_class=AddSubmissionForm, context={
        'title': 'Add submission',
        'return_url': reverse('submissions:get_list'),
        'initial': {
            'fund': request.user.fund,
            'author': request.user
        }
    })


@user_passes_test(user_should_be_volunteer)
@require_GET
def get_submission_details(request, id):
    submission = get_object_or_404(
        Submission.objects.filter(fund=request.user.fund), pk=id)
    paginator = Paginator(submission.wards.all(), DEFAULT_PAGE_SIZE)
    return render(request, 'submission_details.html', {
        'submission': submission,
        'items_count': paginator.count,
        'page': paginator.get_page(request.GET.get('page')),
    })


@user_passes_test(user_should_be_volunteer)
@require_http_methods(['GET', 'POST'])
def edit_submission(request, id):
    submission = get_object_or_404(
        Submission.objects.filter(fund=request.user.fund), pk=id)

    return_url = reverse('submissions:get_submission_details', args=[id])
    if not submission_can_be_edited(submission, request.user):
        raise ApplicationError('Submission cannot be edited.', return_url)

    return render_generic_form(request, form_class=AddSubmissionForm, context={
        'title': 'Edit submission',
        'return_url': return_url,
        'instance': submission,
        'initial': {
            'fund': request.user.fund,
            'author': request.user
        }
    })


@user_passes_test(user_should_be_volunteer)
@require_POST
def remove_submission(request, id):
    submission = get_object_or_404(
        Submission.objects.filter(fund=request.user.fund), pk=id)
    return_url = reverse('submissions:get_list')

    if not submission_can_be_edited(submission, request.user):
        raise ApplicationError(
            'Submission cannot be removed. It is in progress', return_url)

    submission.delete()

    return redirect(return_url)


@user_passes_test(user_should_be_volunteer)
@require_POST
def send_submission(request, id):
    submission = get_object_or_404(
        Submission.objects.filter(fund=request.user.fund), pk=id)

    submission.save()
    
    from django.conf import settings
    send_submssions.apply_async(args=[submission.id], queue=settings.DEFAULT_QUEUE_NAME)

    return redirect(reverse('submissions:get_submission_details', args=[id]))


@user_passes_test(user_should_be_volunteer)
@require_http_methods(['GET', 'POST'])
def add_submission_ward(request, id):
    submission = get_object_or_404(
        Submission.objects.filter(fund=request.user.fund), pk=id)

    if not submission_can_be_edited(submission, request.user):
        raise ApplicationError(
            'Ward cannot be added to submission.',
            reverse('submissions:get_submission_details', args=[id]))

    if request.method == 'POST':
        form = AttachWardToTargetForm(request.POST, initial={
            'target': submission})
        if form.is_valid():
            form.save()

    request.method = 'GET'
    return render(request, 'add_submission_ward.html', {
        'model_name': 'submission',
        'submission': submission
    })


@user_passes_test(user_should_be_volunteer)
@require_POST
def remove_submission_ward(request, id, ward_id):
    submission = get_object_or_404(
        Submission.objects.filter(fund=request.user.fund), pk=id)
    ward = get_object_or_404(submission.wards, pk=ward_id)
    submission.wards.remove(ward)

    return redirect(reverse('submissions:get_submission_details', args=[id]))

charity/submissions/templates/add_submission_ward.html
{% extends 'base.html' %}
{% block content %}
{% load customtags %}
<h2 class="mt-4">Add ward to {{ submission.name }}</h2>
<ol class="breadcrumb mb-4">
  <li class="breadcrumb-item">
    <a href="{% url 'funds:get_details' submission.fund_id %}">{{ submission.fund.name }}</a>
  </li>
  <li class="breadcrumb-item">
    <a href="{% url 'submissions:get_list' %}">Submission list</a>
  </li>
  <li class="breadcrumb-item">
    <a href="{% url 'submissions:get_submission_details' submission.id %}">{{ submission.name }}</a>
  </li>
  <li class="breadcrumb-item active">Adding ward</li>
</ol>
{% render_partial 'wards.views.get_filter_list_partial' model=model_name target_id=submission.id %}
{% endblock %}

charity/submissions/templates/submission_details.html
{% extends 'base.html' %}
{% block content %}
{% load submissionfilters %}
<h2 class="mt-4">{{ submission.name }}</h2>
<ol class="breadcrumb mb-4">
  <li class="breadcrumb-item">
    <a href="{% url 'funds:get_details' submission.fund_id %}">{{ submission.fund.name }}</a>
  </li>
  <li class="breadcrumb-item">
    <a href="{% url 'submissions:get_list' %}">Submission list</a>
  </li>
  <li class="breadcrumb-item active">Submission Details</li>
</ol>
<div class="card mb-4">
  <div class="card-body">
    <div class="row">
      <div class="col">
        <div class="bg-light text-dark">
          <strong>Description</strong>: {{ submission.notes }}
        </div>
      </div>
      <div class="col">
        <div class="bg-light text-dark">
          <div>
            <strong>Created</strong>: {{ submission.date_created }}
          </div>
          <div>
            <strong>Author</strong>: <a href="{% url 'funds:get_volunteer_details' submission.author.volunteer_profile.id %}">{{ submission.author.username }}</a>
          </div>
          <div>
            <strong>Mailing group</strong>:<a href="{% url 'mailings:get_group_details' submission.mailing_group.id %}">
              {{submission.mailing_group.name}}</a>
          </div>
          <div>
            <strong>Mailing template</strong>:<a href="{% url 'mailings:edit_template' submission.mailing_template.id %}">
              {{submission.mailing_template.name}}</a>
          </div>
          <div>
            <strong>Status</strong>:
              <span class="badge bg-primary">
                {{submission.status}}
              </span>
          </div>
        </div>
      </div>
    </div>
    <div class="row mt-2">
      <div class="row">
        <div class="col-1">
          <i class="fa-solid fa-pen-to-square"></i>
          <a {% if submission|submission_can_be_edited:user %}
              href="{% url 'submissions:edit_submission' submission.id %}"
             {% else %}
              class="link-disabled"
             {% endif %}>Edit</a>
        </div>
        <div class="col-2">
          <i class="fa-solid fa-paper-plane"></i>
          <a {% if submission|submission_can_be_edited:user %}
                href="{% url 'submissions:send_submission' submission.id %}" 
                class="post-request"
             {% else %}
                class="link-disabled"
             {% endif %}>Send</a>
        </div>
      </div>
    </div>
  </div>
</div>
{% include "partials/submission_wards_list.html" %}
{% endblock %}

charity/submissions/templates/submissions_list.html
{% extends 'base.html' %}
{% block content %}
{% load customtags %}
{% load submissionfilters %}
{% include "partials/header.html" with title='Wards submission' %}
<div>
  <a href="{% url 'submissions:add_submission' %}" class="btn btn-link">Add submission</a>
</div>
<div class="card mb-4">
  <div class="card-header">
    {{ items_count }} <i class="fa-regular fa-paper-plane"></i>
    Submission lists
  </div>
  <div class="card-body">
    <table class="table table-striped">
      <tbody>
        {% for submission in page %}
        <tr>
          <td class="col-3 align-middle">
            <h6>
              <a href="{% url 'submissions:get_submission_details' submission.id %}">{{submission.name}}</a>
            </h6>
            {{submission.date_created}}
            <span class="badge bg-primary">
              {{submission.status}}
            </span>
          </td>
          <td class="col-3 align-middle">
            <span data-bs-toggle="tooltip" data-bs-placement="top" title="Mail group">
              <i class="fa-solid fa-at fa-xs"></i>
              <a href="{% url 'mailings:get_group_details' submission.mailing_group.id %}">
                {{submission.mailing_group.name}}
              </a>
            </span>
          </td>
          <td class="align-middle">
            <span data-bs-toggle="tooltip" data-bs-placement="top" title="Mail template">
              <i class="fa-solid fa-book-open"></i>
              <a href="{% url 'mailings:edit_template' submission.mailing_template.id %}">
                {{submission.mailing_template.name}}
              </a>
            </span>
          </td>
          <td class="align-middle">
            <span data-bs-toggle="tooltip" data-bs-placement="top" title="Author">
              {% include 'partials/user_image_part.html' with user=submission.author %}
            </span>
          </td>
          <td class="align-middle">
            <a {% if submission|submission_can_be_edited:user %}
                 href="{% url 'submissions:remove_submission' submission.id %}"
                 class="post-request"
               {% else %}
                 class="link-disabled"
               {% endif %}>Remove</a>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
{% include 'partials/js.html' %}
{% include 'generic_errormodal.html' %}
{% endblock %}