charity/budgets/urls.py
from django.urls import path

from . import views

app_name = "budgets"

urlpatterns = [
    path('add', views.add_budget, name='create'),
    path('', views.get_budgets_list, name='get_list'),
    path('<uuid:id>/details/', views.get_budget_details, name='get_details'),
    path('<uuid:id>/edit/', views.edit_details, name='edit_details'),
    path('<uuid:id>/remove/', views.remove_budget, name='remove'),
    path('<uuid:id>/excess_contributions/add/',
         views.add_budget_excess_contribution, name="add_budget_excess_contribution"),
    path('<uuid:id>/expenses_planing/',
         views.budget_expenses_planing, name='expenses_planing'),
    path('<uuid:id>/expenses/add/', views.add_budget_expense, name='add_expenses'),
    path('<uuid:id>/incomes/add/', views.add_budget_income, name='add_income'),
    path("<uuid:id>/incomes/<uuid:income_id>/details/",
         views.get_income_details, name="get_income_details"),
    path('<uuid:id>/expenses/<uuid:expense_id>/details/',
         views.get_expense_details, name='get_expense_details'),
    path('<uuid:id>/incomes/<uuid:income_id>/approvements/add/',
         views.approve_budget_income, name='approve_budget_income'),
    path('<uuid:id>/expenses/<uuid:expense_id>/approvements/add/',
         views.approve_budget_expense, name='approve_budget_expense'),
    path('<uuid:id>/approve/', views.approve_budget, name='approve_budget'),
    path('<uuid:id>/reviewers/add/', views.add_budget_reviewer,
         name='add_budget_reviewer'),
    path('<uuid:id>/reviewers/<int:reviewer_id>/remove/',
         views.remove_budget_reviewer, name='remove_budget_reviewer'),
    path('<uuid:id>/reviewers/<int:reviewer_id>/details/',
         views.get_reviewer_details, name='get_reviewer_details'),
    path('<uuid:id>/expenses/<uuid:expense_id>/remove/',
         views.remove_budget_expense, name='remove_budget_expense'),
    path('<uuid:id>/incomes/<uuid:income_id>/remove/',
         views.remove_budget_income, name='remove_budget_income'),
    path('<uuid:id>/incomes/<uuid:income_id>/edit/',
         views.edit_budget_income_details, name='edit_income_details'),
    path('<uuid:id>/expenses/<uuid:expense_id>/edit/',
         views.edit_budget_expense_details, name='edit_expense_details'),
]

charity/charity/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

from commons import views as common_views

urlpatterns = [
    path("accounts/login/", common_views.azure_ad_login, name='login'),
    path('accounts/login/callback/', common_views.azure_ad_callback, name='azure_ad_callback'),
    path('accounts/approve_waiting', common_views.user_is_not_approved, name='user_is_not_approved'),
    path("accounts/logout/", common_views.ad_logout, name='logout'),
    path('admin/', admin.site.urls),
    path('budgets/', include('budgets.urls')),
    path('comments/', include('comments.urls')),
    path('customfields/', include('customfields.urls')),
    path('files/', include('files.urls')),
    path('filters/', include('filters.urls')),
    path('funds/', include('funds.urls')),
    path('notifications/<uuid:id>/details/',
         common_views.view_notification_details, name='view_notification_details'),
    path('mailings/', include('mailings.urls')),
    path('processes/', include('processes.urls')),
    path('projects/', include('projects.urls')),
    path('submissions/', include('submissions.urls')),
    path('tasks/', include('tasks.urls')),
    path('wards/', include('wards.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

charity/files/urls.py
from django.urls import path

from . import views

app_name = "files"

urlpatterns = [
    path('<uuid:id>/', views.get_file, name='get_file'),
    path('content_types/<str:model>/items/<uuid:target_id>/attach/',
         views.attach_file, name='attach_file'),
    path('<uuid:id>/content_types/<str:model>/items/<uuid:target_id>/remove/',
         views.remove_file, name='remove_file'),
    path('<uuid:id>/content_types/<str:model>/items/<uuid:target_id>/change_access/', views.change_file_access, name='change_file_access')
]

charity/funds/urls.py
from django.urls import path

from . import views

app_name = "funds"

urlpatterns = [
    path('', views.get_list, name='get_list'),
    path('<uuid:id>/details/', views.get_details, name='get_details'),
    path('index/partial/', views.get_current_details_partial, name='get_current_details_partial'),
    path('index/',views.get_current_details, name='get_current_details'),
    path('index/volunteers/<uuid:id>/details/', views.get_volunteer_details, name='get_volunteer_details'),
    path('index/contributions/add/', views.add_contribution, name='add_contribution'),
    path('index/contributions/<uuid:id>/details/', views.get_contribution_details, name='get_contribution_details'),
    path('index/contributions/<uuid:id>/remove/', views.remove_contribution, name='remove_contribution'),
    path('index/volunteers/add/', views.add_volunteer, name='add_volunteer'),
    path('index/volunteers/<uuid:id>/edit/', views.edit_volunteer_profile, name='edit_volunteer_profile'),
    path('index/volunteers/<uuid:id>/cover/', views.add_volunteer_cover, name='add_volunteer_cover'),
    path('index/contributors/add/', views.add_contributor, name='add_contributor'),
    path('index/contributors/<uuid:id>/details/', views.get_contributor_details, name='get_contributor_details'),
    path('index/contributors/<uuid:id>/edit/', views.edit_contributor_details, name='edit_contributor_details')
]

charity/funds/forms.py
from django import forms
from django.contrib.auth.models import User

from commons.mixins import FormControlMixin, InitialMixin, FileUploadMixin
from commons.functional import validate_modelform_field
from .models import Fund, Contribution, Contributor, VolunteerProfile


class FundForm(forms.ModelForm):
    class Meta:
        model = Fund
        exclude = ('date_created', )


class CreateContributionForm(
        forms.ModelForm, InitialMixin, FormControlMixin):
    __initial__ = ['fund', 'author']

    field_order = ['contributor']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        InitialMixin.__init__(self)
        FormControlMixin.__init__(self)

        self.form.fund.widget = forms.HiddenInput()
        self.form.contributor.queryset = Contributor.objects \
            .filter(fund=self.fund, is_internal=False)

    def clean(self):
        validate_modelform_field('fund', self.initial, self.cleaned_data)
        return self.cleaned_data

    def save(self):
        self.instance.author = self.author

        return super().save()

    class Meta:
        model = Contribution
        exclude = ['id', 'date_created', 'author']


class CreateVolunteerForm(
        forms.ModelForm, InitialMixin, FormControlMixin):
    __initial__ = ['fund']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        InitialMixin.__init__(self)
        FormControlMixin.__init__(self)

        self.form.user.queryset = User.objects.filter(
            volunteer_profile__isnull=True,
            is_active=True
        )
        self.form.fund.widget = forms.HiddenInput()

    def clean(self):
        validate_modelform_field('fund', self.initial, self.cleaned_data)
        return self.cleaned_data

    class Meta:
        model = VolunteerProfile
        exclude = ['id', 'date_created', 'cover']


class CreateContributorForm(
        forms.ModelForm, InitialMixin, FormControlMixin, FileUploadMixin):
    __initial__ = ['fund']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        InitialMixin.__init__(self)
        FormControlMixin.__init__(self)

        self.form.fund.widget = forms.HiddenInput()

    def clean(self):
        validate_modelform_field('fund', self.initial, self.cleaned_data)
        return self.cleaned_data

    class Meta:
        model = Contributor
        exclude = ['id', 'date_created']


class UpdateVolunteerProfile(
        forms.ModelForm, InitialMixin, FormControlMixin):
    __initial__ = ['fund']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        InitialMixin.__init__(self)
        FormControlMixin.__init__(self)

        self.form.fund.widget = forms.HiddenInput()

    def clean(self):
        validate_modelform_field('fund', self.initial, self.cleaned_data)
        return self.cleaned_data

    class Meta:
        model = VolunteerProfile
        exclude = ['id',
                   'date_created',
                   'user',
                   'cover']

charity/funds/views.py
from django.contrib.auth.decorators import user_passes_test
from django.core.paginator import Paginator
from django.shortcuts import redirect, render, get_object_or_404
from django.urls import reverse
from django.views.decorators.http import require_http_methods, require_GET, require_POST

from commons import DEFAULT_PAGE_SIZE
from commons.exceptions import ApplicationError
from commons.functional import user_should_be_volunteer, user_should_be_superuser, \
    render_generic_form, wrap_dicts_page_to_objects_page

from budgets.models import Income

from .querysets import get_contributor_budgets_queryset, get_contributions_queryset, \
    get_contribution_details_queryset
from .messages import Warnings
from .models import Contribution, Contributor, Fund, VolunteerProfile
from .forms import CreateContributionForm, CreateVolunteerForm, \
    CreateContributorForm, UpdateVolunteerProfile
from .requirements import contribution_is_ready_to_be_removed


@user_passes_test(user_should_be_superuser)
@require_GET
def get_list(request):
    paginator = Paginator(Fund.objects.order_by('id'), DEFAULT_PAGE_SIZE)
    return render(request, 'funds_list.html', {
        'fund_page': paginator.get_page(request.GET.get('page'))
    })


@user_passes_test(user_should_be_volunteer)
@require_GET
def get_details(request, id):
    default_tab = 'contributions'
    tabs = {
        'contributions': lambda fund: get_contributions_queryset(fund),
        'contributors': lambda fund: fund.contributors.all(),
        'volunteers': lambda fund: fund.volunteers.all(),
    }

    fund = get_object_or_404(Fund, pk=id)
    tab = request.GET.get('tab', default_tab)

    if not tab in tabs:
        tab = default_tab

    queryset = tabs.get(tab)(fund)
    paginator = Paginator(queryset, DEFAULT_PAGE_SIZE)

    if tab == 'contributions':
        page = wrap_dicts_page_to_objects_page(
            paginator.get_page(request.GET.get('page')), model=Contribution)
    else:
        page = paginator.get_page(request.GET.get('page'))

    return render(request, 'fund_details.html', {
        'title': 'Fund',
        'fund': fund,
        'selected_tab': tab,
        'items_count': paginator.count,
        'tabs': tabs.keys(),
        'page': page
    })


@user_passes_test(user_should_be_volunteer)
@require_GET
def get_current_details_partial(request,  *args, **kwargs):
    return render(request, 'partials/fund_details.html', {
        'title': kwargs.get('title'),
        'fund': get_object_or_404(Fund, pk=request.user.fund.id)
    })


@user_passes_test(user_should_be_volunteer)
@require_GET
def get_current_details(request):
    return get_details(request, request.user.fund.id)


@user_passes_test(user_should_be_volunteer)
@require_http_methods(['GET', 'POST'])
def add_contributor(request):
    return render_generic_form(
        request=request,
        form_class=CreateContributorForm,
        context={
            'title': 'Add contributor',
            'return_url': '%s?%s' % (reverse('funds:get_current_details'), 'tab=contributors'),
            'initial': {
                'fund': request.user.fund
            }
        }
    )


@user_passes_test(user_should_be_volunteer)
@require_GET
def get_contributor_details(request, id):
    contributor = get_object_or_404(
        Contributor.objects.filter(
            fund=request.user.fund), pk=id)

    queryset = get_contributor_budgets_queryset(contributor)

    paginator = Paginator(queryset, DEFAULT_PAGE_SIZE)
    page = wrap_dicts_page_to_objects_page(
        paginator.get_page(request.GET.get('page')))

    return render(request, 'fund_contributor_details.html', {
        'contributor': contributor,
        'page': page
    })


@user_passes_test(user_should_be_volunteer)
@require_http_methods(['GET', 'POST'])
def edit_contributor_details(request, id):
    return render_generic_form(request, form_class=CreateContributorForm, context={
        'title': 'Edit contributor',
        'return_url': reverse('funds:get_contributor_details', args=[id]),
        'initial': {
            'fund': request.user.fund
        },
        'instance': get_object_or_404(
            Contributor.objects.filter(
                fund=request.user.fund),
            pk=id)
    })


@user_passes_test(user_should_be_volunteer)
@require_http_methods(['GET', 'POST'])
def add_contribution(request):
    return render_generic_form(
        request=request,
        form_class=CreateContributionForm,
        context={
            'title': 'Add contribution',
            'return_url': '%s?%s' % (reverse('funds:get_current_details'), 'tab=contributions'),
            'initial': {
                'fund': request.user.fund,
                'author': request.user
            }
        })


@user_passes_test(user_should_be_volunteer)
@require_GET
def get_contribution_details(request, id):
    contribution = get_object_or_404(
        Contribution.objects.filter(
            fund=request.user.fund),
        pk=id)
    queryset = get_contribution_details_queryset(contribution)

    paginator = Paginator(queryset, DEFAULT_PAGE_SIZE)
    page = wrap_dicts_page_to_objects_page(
        paginator.get_page(request.GET.get('page')), model=Income)
    return render(request, 'fund_contribution_details.html', {
        'title': 'Contribution',
        'contribution': contribution,
        'page': page
    })


@user_passes_test(user_should_be_volunteer)
@require_POST
def remove_contribution(request, id):
    return_url = f'{reverse("funds:get_current_details")}?tab=contributions'
    contribution = get_object_or_404(request.user.fund.contributions, pk=id)
    if not contribution_is_ready_to_be_removed(contribution, request.user):
        raise ApplicationError(
            Warnings.CONTRIBUTION_IS_NOT_READY_TOBE_REMOVED, return_url)

    if contribution.contributor.is_internal:
        if contribution.tasks.filter(project__is_closed=True).exists():
            raise ApplicationError(
                Warnings.CONTRIBUTION_IS_INTERNAL_AND_LINKED_PROJECT_IS_CLOSED, return_url)

    contribution.delete()
    return redirect(return_url)


@user_passes_test(user_should_be_volunteer)
@require_http_methods(['GET', 'POST'])
def add_volunteer(request):
    return render_generic_form(
        request=request,
        form_class=CreateVolunteerForm,
        context={
            'title': 'Add volunteer',
            'return_url': '%s?%s' % (reverse('funds:get_current_details'), 'tab=volunteers'),
            'initial': {
                'fund': request.user.fund
            }
        }
    )


@user_passes_test(user_should_be_volunteer)
@require_GET
def get_volunteer_details(request, id):
    volunteer = get_object_or_404(
        VolunteerProfile.objects.filter(
            fund=request.user.fund),
        pk=id)
    return render(request, 'fund_volunteer_details.html', {
        'volunteer': volunteer
    })


@user_passes_test(user_should_be_volunteer)
@require_POST
def add_volunteer_cover(request, id):
    cover = request.FILES['cover']
    if cover:
        volunteer = get_object_or_404(
            VolunteerProfile.objects.filter(
                fund=request.user.fund), pk=id)
        volunteer.cover = cover
        volunteer.save()

    return redirect(reverse('funds:get_volunteer_details', args=[id]))


@user_passes_test(user_should_be_volunteer)
@require_http_methods(['GET', 'POST'])
def edit_volunteer_profile(request, id):
    volunteer = get_object_or_404(
        VolunteerProfile.objects.filter(
            fund__id=request.user.fund.id), pk=id)

    return render_generic_form(
        request=request, form_class=UpdateVolunteerProfile,
        context={
            'title': 'Edit volunteer',
            'return_url': reverse('funds:get_volunteer_details', args=[id]),
            'instance': volunteer,
            'initial': {
                'fund': request.user.fund
            },
        })

charity/funds/templates/fund_contribution_details.html
{% extends 'base.html' %}
{% block content %}
{% load customtags %}
<h2 class="mt-4">Contribution {{ contribution.date_created }}</h2>
  <h2 class="mt-4">{{ process.name }}</h2>
  <ol class="breadcrumb mb-4">
    <li class="breadcrumb-item active">
      <a href="{% url 'funds:get_current_details'%}?tab=contributions"> {{ user.fund.name }} </a>
    </li>
    <li class="breadcrumb-item active">Contribution Details</li>
  </ol>
  <div class="card mb-4">
    <div class="card-body">
        <div class="row">
            <div class="col">
              <div class="bg-light text-dark">
                 <strong>Description</strong>: {{ contribution.notes }}
              </div>
            </div>
            <div class="col">
              <div class="bg-light text-dark">
                <div>
                  {{ contribution.contributor|thumbnail:50 }}
                  <a href="{% url 'funds:get_contributor_details' contribution.contributor_id %}"> {{ contribution.contributor.name }} </a>
                </div>
                <div>
                  <strong>Contribution date</strong>: {{ contribution.contribution_date }}
                </div>
                <div>
                  <strong>Created</strong>: {{ contribution.date_created}}
                </div>
                <div>
                  <strong>Author</strong>: <a href="{% url 'funds:get_volunteer_details' contribution.author.volunteer_profile.id %}">{{ contribution.author.username }}</a>
                </div>
                <div>
                  <strong>Amount</strong>: {{ contribution.amount|floatformat:'2g' }}
                </div>
                <div>
                  <strong>Available Amount</strong>: {{ contribution.available_amount|floatformat:'2g'}}
                </div>
              </div>  
            </div>
        </div>
      </div>
  </div>
  <div class="card mb-4">
    <div class="card-header">
      <i class="fas fa-sack-dollar"></i>
      Budgets
    </div>
    <div class="card-body">
      <table class="table table-striped">
        <tbody>
          {% for budget in page %}
            <tr>
              <td class="col-3">
                <h6>
                  <a href="{% url 'budgets:get_details' budget.budget.id %}">{{ budget.budget.name }}</a>
                </h6>
                {{ budget.budget.date_created }}
              </td>
              <td class="col-2 align-middle">
                <i class="fa-solid fa-dollar-sign fa-xs"></i>
                {{ budget.budget_amount|floatformat:'2g' }}
              </td>
              <td class="align-middle">
                {% include 'partials/td_approvement_part.html' with approvement=budget.budget.approvement %}
              </td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
      {% include 'paginator.html' with obj_page=page %}
    </div>
  </div>
{% endblock %}

charity/funds/templates/fund_contributor_details.html
{% extends 'base.html' %}
{% block content %}
{% load customtags %}
<h2 class="mt-4">{{ contributor.name }}</h2>
  <ol class="breadcrumb mb-4">
    <li class="breadcrumb-item">
      <a href="{% url 'funds:get_current_details' %}?tab=contributors">{{ contributor.fund.name}}</a>
    </li>
    <li class="breadcrumb-item active">Contributor Details</li>
  </ol>
  <div class="card mb-4">
    <div class="card-body">
      <div class="row">
        <div class="col-2">
          <div class="bg-light text-dark">
            <div class="card">
              {% if contributor.cover %}
                <img src="{{ contributor.cover.url }}" alt="Upload cover" />
              {% else %}
                <img src="..." alt="Upload cover" />
              {% endif %}
            </div>
          </div>
        </div>
        <div class="col">
          <div class="bg-light text-dark">
            <div>
              <strong>Created</strong>: {{ contributor.date_created }}
            </div>
            <div>
              <strong>Web site</strong>: 
              <a href="{{ contributor.website }}">{{ contributor.website }}</a>
            </div>
            <div>
              <strong>Mobile phone</strong>: {{ contributor.mobile_phone|phone_number }}
            </div>
            <div>
              <strong>Email</strong>:
              {% if contributor.email  %}
                <a href="mailto:{{ contributor.email }}">{{ contributor.email }}</a>
              {% endif %}
            </div>
           
            <div>
              <strong>Type</strong>: 
              {% if contributor.is_company %}
                <span class="badge bg-primary">company</span>
              {% else %}
                <span class="badge bg-primary">person</span>
              {% endif %}
            </div>
            <div>
              <i class="fa-solid fa-pen-to-square"></i>
              <a href="{% url 'funds:edit_contributor_details' contributor.id %}">Edit</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>  
  <div class="card mb-4">
    <div class="card-header">
      <i class="fas fa-sack-dollar"></i>
      Budgets
    </div>
    <div class="card-body">
      <table class="table table-striped">
        <tbody>
          {% for budget in page %}
            <tr>
              <td class="col-3">
                <h6>
                  <a href="{% url 'budgets:get_details' budget.budget.id %}">{{ budget.budget.name }}</a>
                </h6>
                {{ budget.budget.date_created }}
              </td>
              <td class="col-2 align-middle">
                <i class="fa-solid fa-dollar-sign fa-xs"></i>
                {{ budget.budget_amount|floatformat:'2g' }}
              </td>
              <td class="align-middle">
                {% include 'partials/td_approvement_part.html' with approvement=budget.budget.approvement %}
              </td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
      {% include 'paginator.html' with obj_page=page %}
    </div>
  </div>
{% endblock %}

charity/funds/templates/fund_details.html
{% extends 'base.html' %}
{% block content %}
  <h2 class="mt-4">{{ fund.name }}</h2>
  <ol class="breadcrumb mb-4">
    <li class="breadcrumb-item active">Fund Details</li>
  </ol>
  <div class="card mb-4">
    <div class="card-body">
      <div class="row">
        <div class="col">
          <div class="bg-light text-dark">
            <strong>Description</strong>: {{ fund.notes }}
          </div>
        </div>
        <div class="col">
          <div class="bg-light text-dark">
            <div>
              <strong>Created</strong>: {{ fund.date_created }}
            </div>
            <div>
              <strong>Budget</strong>: {{ fund.active_budget_amount|floatformat:'2g' }}
            </div>
            <div>
              <strong>Volunteers</strong>: {{ fund.total_volunteers_count }}
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <ul class="nav nav-pills mb-3">
    {% for tab in tabs %}
      <li class="nav-item" role="presentation">
        {% if selected_tab == tab %}
          <a href="?tab={{ tab }}" class="nav-link active">
            {{ tab|capfirst }}
          </a>
        {% else %}
          <a href="?tab={{ tab }}" class="nav-link">{{ tab|capfirst }}</a>
        {% endif %}
      </li>
    {% endfor %}
  </ul>
  <div>
    {% for tab in tabs %}
      {% if selected_tab == tab %}
        {% include 'partials/fund_'|add:tab|add:'_list.html' %}
      {% endif %}
    {% endfor %}
  </div>
{% endblock %}

charity/funds/templates/fund_volunteer_details.html
{% extends 'base.html' %}
{% block content %}
{% load customtags %}
  <h2 class="mt-4">{{ volunteer.user.username }}</h2>

  <ol class="breadcrumb mb-4">
    <li class="breadcrumb-item">
      <a href="{% url 'funds:get_details' volunteer.fund_id %}?tab=volunteers">{{ volunteer.fund.name }}</a>
    </li>
    <li class="breadcrumb-item active">Volunteer Details</li>
  </ol>
  <div class="card mb-4">
    <div class="card-body">
      <div class="row">
        <div class="col-2">
          <div class="bg-light text-dark">
            <div class="card">
              {% if volunteer.cover %}
                <img src="{{ volunteer.cover.url }}" alt="Upload cover" />
              {% else %}
                <img src="..." alt="Upload cover" />
              {% endif %}
              <form method="POST" action="{% url 'funds:add_volunteer_cover' volunteer.id %}" enctype="multipart/form-data">
                {% csrf_token %}
                <label class="btn btn-link">
                  <i class="fa-solid fa-cloud-arrow-up"></i>
                  <input class="form-control" type="file" accept=".png, .jepg, .jpg" name="cover" id="cover" onchange="javascrupt:this.form.submit()" style="display:none;" />
                </label>
              </form>
            </div>
          </div>
        </div>
        <div class="col">
          <div class="bg-light text-dark">
            <div>
              <strong>Created</strong>: {{ volunteer.date_created }}
            </div>
            <div>
              <strong>User name</strong>: {{ volunteer.user.username }}
            </div>
            <div>
              <strong>Full name</strong>: {{ volunteer.user.first_name }} {{ volunteer.user.last_name }}
            </div>
            <div>
              <strong>Title</strong>: {{ volunteer.title }}
            </div>
            <div>
              <strong>Mobile phone</strong>: {{ volunteer.mobile_phone|phone_number }}
            </div>
            <div>
              <strong>Email</strong>:
              {% if volunteer.user.email  %}
                <a href="mailto:{{ volunteer.user.email }}">{{ volunteer.user.email }}</a>
              {% endif %}
            </div>
            <div>
              <strong>Last login</strong>: {{ volunteer.user.last_login }}
            </div>
            <div>
              <strong>State</strong>: 
              {% if volunteer.user.is_active %}
                <span class="badge bg-primary" >active</span>
              {% else %}
              <span>inactive</span>
              {% endif%}
            </div>
            <div>
              <i class="fa-solid fa-pen-to-square"></i>
              <a href="{% url 'funds:edit_volunteer_profile' volunteer.id %}">Edit</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

charity/funds/templates/funds_list.html
{% extends 'base.html' %}

{% block content %}
  <h1 class="mt-4">Tables</h1>
  <ol class="breadcrumb mb-4">
    <li class="breadcrumb-item">
      <a href="index.html">Dashboard</a>
    </li>
    <li class="breadcrumb-item active">Tables</li>
  </ol>
  <div class="card mb-4">
    <div class="card-body">
      DataTables is a third party plugin that is used to generate the demo table below. For more information about DataTables, please visit the
      <a target="_blank" href="https://datatables.net/">official DataTables documentation</a>
      .
    </div>
  </div>
  <div class="card mb-4">
    <div class="card-header">
      <i class="fas fa-table me-1"></i>
      Funds
    </div>
    <div class="card-body">
      <table class="table table-bordered">
        <thead>
          <tr>
            <th>Fund name</th>
            <th>Created</th>
            <th>Active projects</th>
            <th>Active budgets</th>
            <th>Wards</th>
            <th>Volunteers</th>
            <th>Contributors</th>
          </tr>
        </thead>
        <tbody>
          {% for fund in fund_page %}
            <tr>
              <td>
                <a href="{% url 'funds:fund_details' fund.id %}">{{ fund.name }}</a>
              </td>
              <td>{{ fund.date_created }}</td>
              <td>{{ fund.active_projects_count }}</td>
              <td>{{ fund.active_budgets_count }}</td>
              <td>{{ fund.total_wards_count }}</td>
              <td>{{ fund.total_volunteers_count }}</td>
              <td>{{ fund.total_contributors_count }} </td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
      {% include 'paginator.html' with obj_page=fund_page %}

    </div>
  </div>
{% endblock %}