charity/budgets/urls.py
from django.urls import path

from . import views

app_name = "budgets"

urlpatterns = [
    path('add', views.add_budget, name='create'),
    path('', views.get_budgets_list, name='get_list'),
    path('<uuid:id>/details/', views.get_budget_details, name='get_details'),
    path('<uuid:id>/edit/', views.edit_details, name='edit_details'),
    path('<uuid:id>/remove/', views.remove_budget, name='remove'),
    path('<uuid:id>/excess_contributions/add/',
         views.add_budget_excess_contribution, name="add_budget_excess_contribution"),
    path('<uuid:id>/expenses_planing/',
         views.budget_expenses_planing, name='expenses_planing'),
    path('<uuid:id>/expenses/add/', views.add_budget_expense, name='add_expenses'),
    path('<uuid:id>/incomes/add/', views.add_budget_income, name='add_income'),
    path("<uuid:id>/incomes/<uuid:income_id>/details/",
         views.get_income_details, name="get_income_details"),
    path('<uuid:id>/expenses/<uuid:expense_id>/details/',
         views.get_expense_details, name='get_expense_details'),
    path('<uuid:id>/incomes/<uuid:income_id>/approvements/add/',
         views.approve_budget_income, name='approve_budget_income'),
    path('<uuid:id>/expenses/<uuid:expense_id>/approvements/add/',
         views.approve_budget_expense, name='approve_budget_expense'),
    path('<uuid:id>/approve/', views.approve_budget, name='approve_budget'),
    path('<uuid:id>/reviewers/add/', views.add_budget_reviewer,
         name='add_budget_reviewer'),
    path('<uuid:id>/reviewers/<int:reviewer_id>/remove/',
         views.remove_budget_reviewer, name='remove_budget_reviewer'),
    path('<uuid:id>/reviewers/<int:reviewer_id>/details/',
         views.get_reviewer_details, name='get_reviewer_details'),
    path('<uuid:id>/expenses/<uuid:expense_id>/remove/',
         views.remove_budget_expense, name='remove_budget_expense'),
    path('<uuid:id>/incomes/<uuid:income_id>/remove/',
         views.remove_budget_income, name='remove_budget_income'),
    path('<uuid:id>/incomes/<uuid:income_id>/edit/',
         views.edit_budget_income_details, name='edit_income_details'),
    path('<uuid:id>/expenses/<uuid:expense_id>/edit/',
         views.edit_budget_expense_details, name='edit_expense_details'),
]

charity/charity/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

from commons import views as common_views

urlpatterns = [
    path("accounts/login/", common_views.azure_ad_login, name='login'),
    path('accounts/login/callback/', common_views.azure_ad_callback, name='azure_ad_callback'),
    path('accounts/approve_waiting', common_views.user_is_not_approved, name='user_is_not_approved'),
    path("accounts/logout/", common_views.ad_logout, name='logout'),
    path('admin/', admin.site.urls),
    path('budgets/', include('budgets.urls')),
    path('comments/', include('comments.urls')),
    path('customfields/', include('customfields.urls')),
    path('files/', include('files.urls')),
    path('filters/', include('filters.urls')),
    path('funds/', include('funds.urls')),
    path('notifications/<uuid:id>/details/',
         common_views.view_notification_details, name='view_notification_details'),
    path('mailings/', include('mailings.urls')),
    path('processes/', include('processes.urls')),
    path('projects/', include('projects.urls')),
    path('submissions/', include('submissions.urls')),
    path('tasks/', include('tasks.urls')),
    path('wards/', include('wards.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

charity/files/urls.py
from django.urls import path

from . import views

app_name = "files"

urlpatterns = [
    path('<uuid:id>/', views.get_file, name='get_file'),
    path('content_types/<str:model>/items/<uuid:target_id>/attach/',
         views.attach_file, name='attach_file'),
    path('<uuid:id>/content_types/<str:model>/items/<uuid:target_id>/remove/',
         views.remove_file, name='remove_file'),
    path('<uuid:id>/content_types/<str:model>/items/<uuid:target_id>/change_access/', views.change_file_access, name='change_file_access')
]

charity/projects/urls.py
from django.urls import path

from . import views

app_name = "projects"

urlpatterns = [
    path('', views.get_list, name='get_list'),
    path('<uuid:id>/details/', views.get_details, name='get_details'),
    path('<uuid:id>/edit/', views.edit_project_details, name='update'),
    path('<uuid:id>/remove/', views.remove_project, name='remove_project'),
    path('<uuid:id>/complete/', views.complete_project, name='complete_project'),
    path('add/', views.add_project, name='create'),
    path('<uuid:id>/add_ward_to_project/', views.add_project_ward, name='add_ward_to_project'),
    path('<uuid:id>/add_process_to_project/', views.add_project_process, name='add_process_to_project'),
    path('<uuid:id>/reviewers/add/', views.add_project_reviewer, name='add_project_reviewer'),
    path('<uuid:id>/reviewers/<int:reviewer_id>/remove/', views.remove_project_reviewer, name='remove_project_reviewer'),
    path('<uuid:id>/reviewers/<int:reviewer_id>/details', views.get_reviewer_details, name='get_reviewer_details'),
    path('<uuid:id>/processes/<uuid:process_id>/remove/', views.remove_project_process, name='remove_project_process'),
    path('<uuid:id>/wards/<uuid:ward_id>/remove/', views.remove_project_ward, name='remove_project_ward'),
    path('<uuid:id>/tasks/<uuid:task_id>/remove/', views.remove_project_task, name='remove_project_task')
]

charity/budgets/views.py
import uuid
from django.db.models import Exists, Q, OuterRef
from django.shortcuts import redirect, render, get_object_or_404
from django.contrib.auth.decorators import user_passes_test
from django.core.paginator import Paginator
from django.views.decorators.http import require_http_methods, require_GET, require_POST
from django.urls import reverse

from commons import DEFAULT_PAGE_SIZE
from commons.exceptions import ApplicationError
from commons.forms import ApprovedOnlySearchForm
from commons.functional import user_should_be_volunteer, render_generic_form, \
    should_be_approved, wrap_dict_set_to_objects_list, wrap_dicts_page_to_objects_page

from funds.models import Approvement
from projects.models import Project
from tasks.querysets import get_estimated_and_not_approved_tasks_queryset, \
    get_project_requested_expenses_queryset
from tasks.models import Expense

from .forms import CreateBudgetForm, CreateIncomeForm, \
    BudgetItemApproveForm, ApproveBudgetForm, UpdateBudgetForm, \
    AddBudgetReviewerForm, CreateExpenseForm, EditBudgetItemForm, \
    CreatePayoutExcessContributionForm, SearchBudgetForm

from .querysets import get_budget_with_avaliable_amounts_queryset
from .functional import get_budget_or_404, get_budget_available_income, validate_pre_requirements
from .messages import Warnings
from .models import Budget, Income


@user_passes_test(user_should_be_volunteer)
@require_GET
def get_budgets_list(request):
    queryset = get_budget_with_avaliable_amounts_queryset(
        request.user.fund)
    
    search_form = SearchBudgetForm(request.user.fund, request.GET)

    paginator = Paginator(search_form.get_search_queryset(queryset), DEFAULT_PAGE_SIZE)
    page = wrap_dicts_page_to_objects_page(
        paginator.get_page(request.GET.get('page')), model=Budget)

    return render(request, 'budgets_list.html', {
        'title': 'Budgets',
        'page': page,
        'search_form': search_form,
        'items_count': paginator.count
    })


@user_passes_test(user_should_be_volunteer)
@require_http_methods(['GET', 'POST'])
def add_budget(request):
    return render_generic_form(
        request=request, form_class=CreateBudgetForm,
        context={
            'return_url': reverse("budgets:get_list"),
            'title': 'Add budget',
            'initial': {
                'fund': request.user.fund,
                'author': request.user,
            }
        })


@user_passes_test(user_should_be_volunteer)
@require_GET
def get_budget_details(request, id):
    default_tab = 'incomes'
    tabs = {
        'incomes': lambda budget:
            budget.incomes.select_related(
                'author', 'author__volunteer_profile', 'approvement'),
        'expenses': lambda budget:
            budget.expenses.select_related(
                'author', 'approvement', 'project'),
        'approvements': lambda budget: budget.approvements.all(),
        'reviewers': lambda budget: budget.reviewers.select_related('volunteer_profile')
    }

    tab = request.GET.get('tab', default_tab)
    if not tab in tabs:
        tab = default_tab

    budget = get_budget_or_404(request, id)

    queryset = tabs.get(tab)(budget)
    search_form = ApprovedOnlySearchForm(request.GET)

    paginator = Paginator(search_form.get_search_queryset(queryset), DEFAULT_PAGE_SIZE)

    return render(request, 'budget_details.html', {
        'title': 'Budget',
        'tabs': tabs.keys(),
        'items_count': paginator.count,
        'budget': budget,
        'selected_tab': tab,
        'page': paginator.get_page(request.GET.get('page')),
        'search_form': search_form
    })


@user_passes_test(user_should_be_volunteer)
@require_http_methods(['GET', 'POST'])
def edit_details(request, id):
    budget = get_budget_or_404(request, id)
    return_url = reverse('budgets:get_details', args=[id])

    validate_pre_requirements(request, budget, return_url)

    return render_generic_form(
        request=request, form_class=UpdateBudgetForm,
        context={
            'return_url': return_url,
            'title': 'Edit budget',
            'initial': {
                'fund': request.user.fund,
                'author': request.user,
            },
            'instance': budget
        })


@user_passes_test(user_should_be_volunteer)
@require_http_methods(['GET', 'POST'])
def approve_budget(request, id):
    budget = get_budget_or_404(request, id)
    return_url = f'{reverse("budgets:get_details", args=[id])}?tab=approvements'

    validate_pre_requirements(request, budget, return_url)

    return render_generic_form(
        request=request,
        form_class=ApproveBudgetForm, context={
            'return_url': return_url,
            'title': 'Add approvement',
            'initial': {
                'author': request.user,
                'fund': request.user.fund,
                'target': budget
            },
        })


@user_passes_test(user_should_be_volunteer)
@require_http_methods(['GET', 'POST'])
def add_budget_excess_contribution(request, id):
    budget = get_budget_or_404(request, id)
    return_url = reverse('budgets:get_details', args=[id])

    return render_generic_form(
        request=request,
        form_class=CreatePayoutExcessContributionForm, context={
            'return_url': return_url,
            'title': 'Add payout excess contribution',
            'initial': {
                'amount': budget.avaliable_income_amount,
                'author': request.user,
                'fund': request.user.fund,
                'budget': budget
            },
        })


@user_passes_test(user_should_be_volunteer)
@require_POST
def remove_budget(request, id):
    budget = get_budget_or_404(request, id)
    return_url = reverse('budgets:get_list')

    validate_pre_requirements(request, budget, return_url)
    if budget.incomes.exists():
        raise ApplicationError(
            Warnings.BUDGET_CANNOT_BE_DELETED_IT_HAS_INCOMES, return_url)

    budget.delete()
    return redirect(return_url)


@user_passes_test(user_should_be_volunteer)
@require_http_methods(['GET', 'POST'])
def add_budget_income(request, id):
    return_url = reverse('budgets:get_details', args=[id])
    budget = get_budget_or_404(request, id)

    validate_pre_requirements(request, budget, return_url)

    return render_generic_form(
        request=request, form_class=CreateIncomeForm,
        context={
            'return_url': return_url,
            'title': 'Add income',
            'initial': {
                'author': request.user,
                'budget': budget
            }
        })


@user_passes_test(user_should_be_volunteer)
@require_http_methods(['GET', 'POST'])
def edit_budget_income_details(request, id, income_id):
    budget = get_budget_or_404(request, id)
    income = get_object_or_404(budget.incomes, pk=income_id)
    return_url = reverse('budgets:get_income_details',
                         args=[budget.id, income_id])

    validate_pre_requirements(request, income, return_url)

    return render_generic_form(
        request=request, form_class=EditBudgetItemForm, context={
            'return_url': return_url,
            'title': 'Edit budget income',
            'initial': {
                'budget': budget,
                'target': income
            }
        }
    )


@user_passes_test(user_should_be_volunteer)
@require_http_methods(['GET', 'POST'])
def approve_budget_income(request, id, income_id):
    budget = get_budget_or_404(request, id)
    income = get_object_or_404(budget.incomes, pk=income_id)
    return_url = reverse('budgets:get_income_details',
                         args=[budget.id, income_id])

    validate_pre_requirements(request, income, return_url, action='approve')

    return render_generic_form(
        request=request,
        form_class=BudgetItemApproveForm, context={
            'return_url': return_url,
            'title': 'Add approvement',
            'initial': {
                'author': request.user,
                'fund': request.user.fund,
                'target': income
            },
        })


@user_passes_test(user_should_be_volunteer)
@require_POST
def remove_budget_income(request, id, income_id):
    budget = get_budget_or_404(request, id)
    return_url = f'{reverse("budgets:get_details", args=[id])}?tab=incomes'

    validate_pre_requirements(request, budget, return_url)

    if should_be_approved(budget):
        raise ApplicationError(
            Warnings.INCOME_CANNOT_BE_DELETED_BUDGET_APPROVED, return_url)

    income = get_object_or_404(budget.incomes, pk=income_id)

    if should_be_approved(income):
        raise ApplicationError(
            Warnings.INCOME_CANNOT_BE_DELETED_IT_HAS_BEEN_APPROVED, return_url)

    income.delete()
    return redirect(return_url)


@user_passes_test(user_should_be_volunteer)
@require_http_methods(['GET', 'POST'])
def add_budget_expense(request, id):
    budget = get_budget_or_404(request, id)
    project_id = request.GET.get('project_id')
    task_id = request.GET.get('task_id')
    return_url = '%s?%s=%s' % (reverse('budgets:expenses_planing', args=[
                               budget.id]), 'project_id', project_id)

    validate_pre_requirements(request, budget, return_url)

    project = get_object_or_404(
        Project.objects.filter(
            fund=request.user.fund,
            is_closed=False),
        pk=project_id)
    task = get_object_or_404(project.tasks.filter(
        expense__isnull=True), pk=task_id)

    return render_generic_form(
        request=request, form_class=CreateExpenseForm,
        context={
            'return_url': return_url,
            'title': 'Add expense',
            'initial': {
                'author': request.user,
                'budget': budget,
                'project': project,
                'task': task
            }
        })


@user_passes_test(user_should_be_volunteer)
@require_http_methods(['GET', 'POST'])

charity/budgets/templates/partials/budget_approvements_list.html
{% load budgetfilters %}
<div>
    <a  {% if budget|budget_can_be_edited:user %}
            href="{% url 'budgets:approve_budget' budget.id %}" 
            class="btn btn-link"
        {% else %}
            class="btn btn-link disabled"
        {% endif %}>Add review</a>
</div>
{% include "approvements_list.html" %}

charity/budgets/templates/partials/budget_expenses_list.html
{% load budgetfilters %}
<div>
  <a  {% if budget|budget_item_can_be_added:user %}
        href="{% url 'budgets:expenses_planing' budget.id %}" class="btn btn-link" 
      {% else %}
        class="btn btn-link disabled" href=""
      {% endif %}>Add expense</a>
</div>
<div class="card mb-4">
  <div class="card-header">
  {{ items_count }} <i class="fas fa-sack-dollar"></i>
    Expenses
  </div>
  <div class="card-body">
    <div>
      <form action="{% url 'budgets:get_details' budget.id %}" method="get">
        <input type="hidden" name="tab" value="expenses">
        <div class="row row-cols-md-4 g-4">
          {% for field in search_form %}
          <div class="col">
            {{field}}
          </div>
          {% endfor %}
        </div>
      </form>
    </div>
    <table class="table table-striped">
      <tbody>
        {% for expense in page %}
          <tr>
            <td class="col-2 align-middle">
              <h6>
                <i class="fa-solid fa-dollar-sign fa-sm"></i>
                <a href="{% url 'budgets:get_expense_details' budget.id expense.id %}">{{ expense.amount|floatformat:'2g' }}</a>
              </h6>
              {{ expense.date_created }}
            </td>
            <td class="col-1 align-middle text-center"> 
              {% include 'partials/td_approvement_part.html' with approvement=expense.approvement %}
            </td>
            <td class="align-middle">
              <span data-bs-toggle="tooltip" data-bs-placement="top" title="Reviewer">
                {% include 'partials/user_image_part.html' with user=expense.reviewer %}
              </span>
            </td>
            <td class="align-middle"> 
              {{ expense.notes }}
            </td>
            <td class="align-middle">
              <span data-bs-toggle="tooltip" data-bs-placement="top" title="Project">
                <a href="{% url 'projects:get_details' expense.project.id %}">{{ expense.project.name }}</a>
              </span>
            </td>
            <td class="align-middle">
              <a {% if expense|budget_item_is_ready_to_be_removed:user %}
                    href="{% url 'budgets:remove_budget_expense' budget.id expense.id %}" 
                    class="post-request"
                  {% else %}
                    href="#" class="link-disabled"
                  {% endif %}>Remove</a>
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
    {% include 'paginator.html' with obj_page=page %}
  </div>
</div>
{% include 'generic_errormodal.html' %}
{% include 'partials/js.html' %}

charity/budgets/templates/partials/budget_incomes_list.html
{% load budgetfilters %}
<div>
  <a {% if budget|budget_item_can_be_added:user %}
        href="{% url 'budgets:add_income' budget.id %}" class="btn btn-link" 
     {% else %}
        class="btn btn-link disabled" href=""
     {% endif %}>Add income</a>
</div>
<div class="card mb-4">
  <div class="card-header">
    {{ items_count }} <i class="fas fa-sack-dollar"></i>
    Incomes
  </div>
  <div class="card-body">
    <div>
      <form action="" method="get">
        <input type="hidden" name="tab" value="incomes">
        <div class="row row-cols-md-4 g-4">
          {% for field in search_form %}
          <div class="col">
            {{field}}
          </div>
          {% endfor %}
        </div>
      </form>
    </div>
    <table class="table table-striped">
      <tbody>
        {% for income in page %}
          <tr>
            <td class="col-2 align-middle">
              <h6>
                <i class="fa-solid fa-dollar-sign fa-sm"></i>
                <a href="{% url 'budgets:get_income_details' budget.id income.id %}">{{ income.amount|floatformat:'2g' }}</a>
              </h6>
              {{ income.date_created }}
            </td>
            <td class="col-1 align-middle text-center"> 
              {% include 'partials/td_approvement_part.html' with approvement=income.approvement %}
            </td>
            <td class="align-middle">
              <span data-bs-toggle="tooltip" data-bs-placement="top" title="Reviewer">
                {% include 'partials/user_image_part.html' with user=income.reviewer %}
              </span>
            </td>
            <td class="align-middle"> 
              {{ income.notes }}
            </td>
            <td class="align-middle">
              <a {% if income|budget_item_is_ready_to_be_removed:user %}
                    href="{% url 'budgets:remove_budget_income' budget.id income.id %}" 
                    class="post-request"
                  {% else %}
                    href="#" class="link-disabled"
                  {% endif %}>Remove</a>
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
    {% include 'paginator.html' with obj_page=page %}
  </div>
</div>
{% include 'generic_errormodal.html' %}
{% include 'partials/js.html' %}

charity/budgets/templates/partials/budget_reviewers_list.html
{% load budgetfilters %}
<div>
    <a  {% if budget|budget_reviewer_can_be_added:user %}
          href="{% url 'budgets:add_budget_reviewer' budget.id %}" 
          class="btn btn-link"
        {% else %}
          class="btn btn-link disabled"
        {% endif %}>Add reviewer</a>
</div>
{% load customtags %}
<div class="card mb-4">
    <div class="card-header">
      {{items_count}} <i class="fas fa-user-friends"></i>
      Reviewers
    </div>
    <div class="card-body">
      <table class="table table-striped">
        <tbody>
          {% for reviewer in page %}
            <tr>
              <td>
                <h6>
                  {{ reviewer.volunteer_profile|cover }}
                  <a href="{% url 'budgets:get_reviewer_details' budget.id reviewer.id %}">{{ reviewer.username }}</a>
                </h6>
                {{ reviewer.volunteer_profile.title }}
              </td>
              <td class="align-middle">
                <a href="{% url 'budgets:remove_budget_reviewer' budget.id reviewer.id %}" class="post-request">
                  Remove
                </a>
              </td>
             </tr>
          {% endfor %}
        </tbody>
      </table>
      {% include 'paginator.html' with obj_page=page %}
    </div>
  </div>
  {% include 'generic_errormodal.html' %}
  {% include 'partials/js.html' %}