charity/budgets/urls.py
from django.urls import path

from . import views

app_name = "budgets"

urlpatterns = [
    path('add', views.add_budget, name='create'),
    path('', views.get_budgets_list, name='get_list'),
    path('<uuid:id>/details/', views.get_budget_details, name='get_details'),
    path('<uuid:id>/edit/', views.edit_details, name='edit_details'),
    path('<uuid:id>/remove/', views.remove_budget, name='remove'),
    path('<uuid:id>/excess_contributions/add/',
         views.add_budget_excess_contribution, name="add_budget_excess_contribution"),
    path('<uuid:id>/expenses_planing/',
         views.budget_expenses_planing, name='expenses_planing'),
    path('<uuid:id>/expenses/add/', views.add_budget_expense, name='add_expenses'),
    path('<uuid:id>/incomes/add/', views.add_budget_income, name='add_income'),
    path("<uuid:id>/incomes/<uuid:income_id>/details/",
         views.get_income_details, name="get_income_details"),
    path('<uuid:id>/expenses/<uuid:expense_id>/details/',
         views.get_expense_details, name='get_expense_details'),
    path('<uuid:id>/incomes/<uuid:income_id>/approvements/add/',
         views.approve_budget_income, name='approve_budget_income'),
    path('<uuid:id>/expenses/<uuid:expense_id>/approvements/add/',
         views.approve_budget_expense, name='approve_budget_expense'),
    path('<uuid:id>/approve/', views.approve_budget, name='approve_budget'),
    path('<uuid:id>/reviewers/add/', views.add_budget_reviewer,
         name='add_budget_reviewer'),
    path('<uuid:id>/reviewers/<int:reviewer_id>/remove/',
         views.remove_budget_reviewer, name='remove_budget_reviewer'),
    path('<uuid:id>/reviewers/<int:reviewer_id>/details/',
         views.get_reviewer_details, name='get_reviewer_details'),
    path('<uuid:id>/expenses/<uuid:expense_id>/remove/',
         views.remove_budget_expense, name='remove_budget_expense'),
    path('<uuid:id>/incomes/<uuid:income_id>/remove/',
         views.remove_budget_income, name='remove_budget_income'),
    path('<uuid:id>/incomes/<uuid:income_id>/edit/',
         views.edit_budget_income_details, name='edit_income_details'),
    path('<uuid:id>/expenses/<uuid:expense_id>/edit/',
         views.edit_budget_expense_details, name='edit_expense_details'),
]

charity/charity/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

from commons import views as common_views

urlpatterns = [
    path("accounts/login/", common_views.azure_ad_login, name='login'),
    path('accounts/login/callback/', common_views.azure_ad_callback, name='azure_ad_callback'),
    path('accounts/approve_waiting', common_views.user_is_not_approved, name='user_is_not_approved'),
    path("accounts/logout/", common_views.ad_logout, name='logout'),
    path('admin/', admin.site.urls),
    path('budgets/', include('budgets.urls')),
    path('comments/', include('comments.urls')),
    path('customfields/', include('customfields.urls')),
    path('files/', include('files.urls')),
    path('filters/', include('filters.urls')),
    path('funds/', include('funds.urls')),
    path('notifications/<uuid:id>/details/',
         common_views.view_notification_details, name='view_notification_details'),
    path('mailings/', include('mailings.urls')),
    path('processes/', include('processes.urls')),
    path('projects/', include('projects.urls')),
    path('submissions/', include('submissions.urls')),
    path('tasks/', include('tasks.urls')),
    path('wards/', include('wards.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

charity/files/urls.py
from django.urls import path

from . import views

app_name = "files"

urlpatterns = [
    path('<uuid:id>/', views.get_file, name='get_file'),
    path('content_types/<str:model>/items/<uuid:target_id>/attach/',
         views.attach_file, name='attach_file'),
    path('<uuid:id>/content_types/<str:model>/items/<uuid:target_id>/remove/',
         views.remove_file, name='remove_file'),
    path('<uuid:id>/content_types/<str:model>/items/<uuid:target_id>/change_access/', views.change_file_access, name='change_file_access')
]

charity/processes/urls.py
from django.urls import path

from . import views

app_name = "processes"

urlpatterns = [
    path('', views.get_list, name='get_list'),
    path('add/', views.create, name='create'),
    path('<uuid:id>/edit/', views.edit_details, name='edit_details'),
    path('<uuid:id>/details/', views.get_details, name='get_details'),
    path('<uuid:id>/create_state', views.create_state, name='create_state'),
    path('<uuid:id>/states/<uuid:state_id>/edit', views.edit_state_details, name='edit_state_details')
]

charity/projects/urls.py
from django.urls import path

from . import views

app_name = "projects"

urlpatterns = [
    path('', views.get_list, name='get_list'),
    path('<uuid:id>/details/', views.get_details, name='get_details'),
    path('<uuid:id>/edit/', views.edit_project_details, name='update'),
    path('<uuid:id>/remove/', views.remove_project, name='remove_project'),
    path('<uuid:id>/complete/', views.complete_project, name='complete_project'),
    path('add/', views.add_project, name='create'),
    path('<uuid:id>/add_ward_to_project/', views.add_project_ward, name='add_ward_to_project'),
    path('<uuid:id>/add_process_to_project/', views.add_project_process, name='add_process_to_project'),
    path('<uuid:id>/reviewers/add/', views.add_project_reviewer, name='add_project_reviewer'),
    path('<uuid:id>/reviewers/<int:reviewer_id>/remove/', views.remove_project_reviewer, name='remove_project_reviewer'),
    path('<uuid:id>/reviewers/<int:reviewer_id>/details', views.get_reviewer_details, name='get_reviewer_details'),
    path('<uuid:id>/processes/<uuid:process_id>/remove/', views.remove_project_process, name='remove_project_process'),
    path('<uuid:id>/wards/<uuid:ward_id>/remove/', views.remove_project_ward, name='remove_project_ward'),
    path('<uuid:id>/tasks/<uuid:task_id>/remove/', views.remove_project_task, name='remove_project_task')
]

charity/tasks/urls.py
from django.urls import path

from . import views

app_name = "tasks"

urlpatterns = [
    path('add/', views.add_task, name='create'),
    path('<uuid:id>/edit/', views.edit_details, name='edit_details'),
    path('<uuid:id>/details/', views.get_details, name='get_details'),
    path('<uuid:id>>/complete/', views.complete_task, name='complete_task'),
    path('<uuid:task_id>/states/<uuid:id>/details/', views.get_state_details, name='get_state_details'),
    path('<uuid:task_id>/states/<uuid:id>/approve/',views.approve_task_state, name='approve_task_state'),
    path('<uuid:task_id>/states/<uuid:id>/request_review/',views.request_task_state_review, name='request_task_state_review'),
    path('<uuid:id>/start_next_state/', views.start_next_state, name='move_to_next_state')
]

charity/wards/urls.py
from django.urls import path

from . import views

app_name = "wards"

urlpatterns = [
    path('', views.get_list, name='get_list'),
    path('<uuid:id>/', views.get_details, name='get_details'),
    path('<uuid:id>/cover/', views.add_ward_cover, name='add_ward_cover'),
    path('create/', views.create, name='create'),
    path('<uuid:id>/edit/', views.edit_details, name='edit_details'),
]

charity/projects/views.py
from django.contrib.auth.decorators import user_passes_test
from django.contrib.auth.models import User
from django.core.paginator import Paginator
from django.db.models import Exists, Q, OuterRef
from django.shortcuts import redirect, render, get_object_or_404
from django.views.decorators.http import require_http_methods, require_GET, require_POST
from django.urls import reverse

from commons import DEFAULT_PAGE_SIZE
from commons.exceptions import ApplicationError
from commons.functional import append_to_url_query, render_generic_form, user_should_be_volunteer, \
    wrap_dicts_page_to_objects_page, get_wrapped_page, get_page

from funds.models import Approvement
from processes.models import Process
from tasks.models import TaskState
from wards.models import Ward
from wards.forms import AttachWardToTargetForm

from .forms import CreateProjectForm, \
    AddProcessToProjectForm, SearchProjetForm, UpdateProjectForm, AddProjectReviewerForm
from .functional import get_project_or_404, validate_pre_requirements
from .querysets import get_project_processes_with_tasks_queryset, \
    get_project_wards_with_tasks_queryset, get_projects_with_tasks_queryset, \
    get_project_rewiewers_with_tasks_queryset
from .messages import Warnings
from .models import Project
from .requirements import process_should_not_be_used_by_any_tasks, \
    project_should_not_contain_any_tasks, reviewer_should_not_be_used_by_any_tasks, \
    ward_should_not_be_used_by_any_tasks, project_is_ready_to_be_completed


@user_passes_test(user_should_be_volunteer)
@require_GET
def get_list(request):
    search_form = SearchProjetForm(request.user.fund, request.GET)
    queryset = get_projects_with_tasks_queryset(
        request.user.fund)
    paginator = Paginator(search_form.get_search_queryset(
        queryset), DEFAULT_PAGE_SIZE)
    page = wrap_dicts_page_to_objects_page(
        paginator.get_page(request.GET.get('page')), model=Project)
    return render(request, 'projects_list.html', {
        'title': 'Projects',
        'page': page,
        'search_form': search_form,
        'items_count': paginator.count
    })


@user_passes_test(user_should_be_volunteer)
@require_http_methods(['GET', 'POST'])
def add_project(request):
    return render_generic_form(
        request=request, form_class=CreateProjectForm,
        context={
            'return_url': reverse('projects:get_list'),
            'title': 'Add project',
            'initial': {
                'author': request.user,
                'fund': request.user.fund
            }
        })


@user_passes_test(user_should_be_volunteer)
@require_GET
def get_details(request, id):
    default_tab = 'tasks'
    page_number = request.GET.get('page')
    tabs = {
        'tasks': lambda project: get_page(
            project.tasks.
            select_related(
                'assignee', 'expense',
                'state',
                'expense__approvement',
                'assignee__volunteer_profile')
            .order_by('order_position'), page_number),
        'processes': lambda project: get_wrapped_page(
            Process, get_project_processes_with_tasks_queryset(project), page_number),
        'wards': lambda project: get_wrapped_page(
            Ward, get_project_wards_with_tasks_queryset(project), page_number),
        'reviewers': lambda project: get_wrapped_page(
            User, get_project_rewiewers_with_tasks_queryset(project), page_number)
    }

    tab = request.GET.get('tab', default_tab)

    if not tab in tabs:
        tab = default_tab

    project = get_object_or_404(Project.objects.filter(
        fund=request.user.fund), pk=id)

    page, count = tabs.get(tab)(project)

    return render(request, 'project_details.html', {
        'title': 'Project',
        'tabs': tabs.keys(),
        'items_count': count,
        'project': project,
        'selected_tab': tab,
        'page': page
    })


@user_passes_test(user_should_be_volunteer)
@require_POST
def remove_project(request, id):
    project = get_project_or_404(request, id)
    return_url = reverse('projects:get_list')

    validate_pre_requirements(request, project, return_url)

    if not project_should_not_contain_any_tasks(project):
        raise ApplicationError(Warnings.PROJECT_TASKS_EXIST, return_url)

    project.delete()

    return redirect(return_url)


@user_passes_test(user_should_be_volunteer)
@require_http_methods(['GET', 'POST'])
def edit_project_details(request, id):
    project = get_project_or_404(request=request, project_id=id)
    return_url = reverse('projects:get_details', args=[project.id])

    validate_pre_requirements(request, project, return_url)

    return render_generic_form(
        request=request, form_class=UpdateProjectForm, context={
            'return_url': return_url,
            'title': 'Edit project',
            'initial': {
                'fund': request.user.fund
            },
            'instance': project
        })


@user_passes_test(user_should_be_volunteer)
@require_POST
def complete_project(request, id):
    project = get_object_or_404(Project, pk=id)
    return_url = reverse('projects:get_details', args=[project.id])

    validate_pre_requirements(request, project, return_url)
    if not project_is_ready_to_be_completed(project):
        raise ApplicationError(Warnings.PROJET_CANNOT_BE_COMPLETED, return_url)

    import datetime
    project.is_closed = True
    project.closed_date = datetime.datetime.utcnow()
    project.save()

    return redirect(return_url)


@user_passes_test(user_should_be_volunteer)
@require_http_methods(['GET', 'POST'])
def add_project_process(request, id):
    project = get_project_or_404(request=request, project_id=id)
    return_url = reverse('projects:get_details', args=[
        project.id]) + '?tab=processes'

    validate_pre_requirements(request, project, return_url)

    return render_generic_form(
        request=request, form_class=AddProcessToProjectForm,
        context={
            'return_url': return_url,
            'title': 'Include process to project',
            'initial': {
                'project': project
            }
        })


@user_passes_test(user_should_be_volunteer)
@require_POST
def remove_project_process(request, id, process_id):
    project = get_project_or_404(request, id)
    return_url = f'{reverse("projects:get_details", args=[id])}?tab=processes'

    validate_pre_requirements(request, project, return_url)

    process = get_object_or_404(project.processes, pk=process_id)

    if not process_should_not_be_used_by_any_tasks(process, project):
        raise ApplicationError(
            Warnings.PROJECT_PROCESS_TASKS_EXIST, return_url)

    project.processes.remove(process)

    return redirect(return_url)


@user_passes_test(user_should_be_volunteer)
@require_http_methods(['GET', 'POST'])
def add_project_ward(request, id):
    project = get_project_or_404(request=request, project_id=id)
    return_url = reverse('projects:get_details', args=[
        project.id]) + '?tab=wards'
    validate_pre_requirements(request, project, return_url)

    def validate_ward(ward):
        from django import forms
        if Project.objects.filter(is_closed=False, fund=ward.fund, wards__in=[ward]).exists():
            raise forms.ValidationError(
                'Ward is alredy used in another project')

    if request.method == 'POST':
        form = AttachWardToTargetForm(request.POST, validators=[
                                      validate_ward], initial={'target': project})
        if form.is_valid():
            form.save()
        else:
            raise ApplicationError(
                'Ward is alredy used in another project',
                f'{reverse("projects:add_ward_to_project", args=[id])}{append_to_url_query(request)}')
        request.method = 'GET'

    return render(request, 'add_project_ward.html', {
        'project': project,
        'model_name': 'project'
    })


@user_passes_test(user_should_be_volunteer)
@require_POST
def remove_project_ward(request, id, ward_id):
    project = get_project_or_404(request, id)
    return_url = f'{reverse("projects:get_details", args=[id])}?tab=wards'

    validate_pre_requirements(request, project, return_url)

    ward = get_object_or_404(project.wards, pk=ward_id)

    if not ward_should_not_be_used_by_any_tasks(ward, project):
        raise ApplicationError(
            Warnings.ASSET_CANNOT_BE_REMOVED_TASKS_EXIST, return_url)

    project.wards.remove(ward)

    return redirect(return_url)


@user_passes_test(user_should_be_volunteer)
@require_http_methods(['GET', 'POST'])
def add_project_reviewer(request, id):
    project = get_project_or_404(request, id)
    return_url = f'{reverse("projects:get_details", args=[id])}?tab=reviewers'

    validate_pre_requirements(request, project, return_url)

    return render_generic_form(
        request=request, form_class=AddProjectReviewerForm, context={
            'return_url': return_url,
            'title': 'Add project reviewer',
            'initial': {
                'project': project
            }
        })


@user_passes_test(user_should_be_volunteer)
@require_POST
def remove_project_reviewer(request, id, reviewer_id):
    project = get_project_or_404(request, id)
    return_url = f'{reverse("projects:get_details", args=[id])}?tab=reviewers'

    validate_pre_requirements(request, project, return_url)

    reviewer = get_object_or_404(project.reviewers, pk=reviewer_id)

    if not reviewer_should_not_be_used_by_any_tasks(reviewer, project):
        raise ApplicationError(
            Warnings.PROJECT_REVIEWER_TASKS_EXIST, return_url)

    if project.leader == reviewer:
        raise ApplicationError(
            Warnings.LEADER_CANNOT_BE_REMOVED_FROM_PROJECT_REVIEWERS, return_url)

    if project.reviewers.count() == 1:
        """redirect to error page with return url"""
        raise ApplicationError(
            Warnings.PROJECT_REVIEWER_MUST_EXISTS, return_url)

charity/projects/templates/partials/project_processes_list.html
{% load projectfilters %}
<div>
  <a {% if project|validate_pre_requirements:user %}
        href="{% url 'projects:add_process_to_project' project.id %}" 
        class="btn btn-link"
      {% else %}
        href="" 
        class="btn btn-link disabled"
      {% endif %}>Add process</a>
</div>
<div class="card mb-4">
  <div class="card-header">
    {{items_count}} <i class="fa-solid fa-gears"></i>
    Processes
  </div>
  <div class="card-body">
    <table class="table table-striped">
      <tbody>
        {% for process in page %}
          <tr>
            <td>
              <h6>
                <a href="{% url 'processes:get_details' process.id %}">{{ process.name }}</a>
              </h6>
              {% if not process.is_inactive %}
                <span class="badge bg-primary">active</span>
              {% else %}
                <span class="badge bg-secondary">inactive</span>
              {% endif %}
            </td>
            <td class="align-middle">
              <a {% if project|validate_pre_requirements:user and process|process_should_bot_be_used_by_any_tasks:project %}
                    href="{% url 'projects:remove_project_process' project.id process.id %}" 
                    class="post-request"
                  {% else %}
                    href="" class="link-disabled"
                  {% endif %}>Remove
              </a>
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
    {% include 'paginator.html' with obj_page=page %}
  </div>
</div>
{% include 'generic_errormodal.html' %}
{% include 'partials/js.html' %}

charity/projects/templates/partials/project_progress.html
<div class="row">
  <div class="col">
    <div class="progress bg-light" style="height: 20px;" data-bs-toggle="tooltip" data-bs-placement="top" title="tasks ({{project.tasks_count}}) done ({{project.done_tasks_count}})">
      <div class="progress-bar" role="progressbar" style="width: {{complete_in_percents}}%;" aria-valuenow="{{complete_in_percents}}" aria-valuemin="0" aria-valuemax="100">{{complete_in_percents}}%</div>
    </div>
  </div>
</div>

charity/projects/templates/partials/project_reviewers_list.html
{% load customtags %}
{% load projectfilters %}
<div>
  <a {% if project|validate_pre_requirements:user %}
        href="{% url 'projects:add_project_reviewer' project.id %}" 
        class="btn btn-link"
      {% else %}
        href="" class="btn btn-link disabled"
      {% endif %}>Add reviewer</a>
</div>
<div class="card mb-4">
  <div class="card-header">
    {{items_count}} <i class="fas fa-user-friends"></i> Reviewers
  </div>
  <div class="card-body">
    <table class="table table-striped">
      <tbody>
        {% for reviewer in page %}
          <tr>
            <td>
              <h6>
                {{ reviewer.volunteer_profile|cover }}
                <a href="{% url 'projects:get_reviewer_details' project.id reviewer.id %}">{{ reviewer.username }}</a>
              </h6>
              {{ reviewer.volunteer_profile.title }}
            </td>
              <td class="align-middle">
                <a {% if project|validate_pre_requirements:user and reviewer|reviewer_should_not_be_used_by_any_tasks:project %}
                      href="{% url 'projects:remove_project_reviewer' project.id reviewer.id %}" 
                      class="post-request"
                    {% else %}
                      href="" class="link-disabled"
                    {% endif %}>Remove</a>
              </td>
            </tr>
        {% endfor %}
      </tbody>
    </table>
    {% include 'paginator.html' with obj_page=page %}
  </div>
</div>
{% include 'generic_errormodal.html' %}
{% include 'partials/js.html' %}

charity/projects/templates/partials/project_task_card.html
<div class="row mt-2">
  <div>
    <div class="card" style="max-width: 18rem;">
      <div class="card-header">
        <div class="row">
          <div class="col">
          </div>
          <div class="col d-flex justify-content-end">
            <div>
              {{comments_count}} <i class="fa-regular fa-message"></i>
            </div>
          </div>
        </div>
      </div>
      <div class="card-body">
        <h5 class="card-title"><a href="{% url 'tasks:get_details' task.id %}">{{ task.name }}</a></h5>
        {% include 'partials/user_image_part.html' with user=task.assignee %}
        <p class="card-text">
          {% if  task.expense %}
            <i class="fa-solid fa-dollar-sign fa-sm"></i>
            <a href="{% url 'budgets:get_expense_details' task.expense.budget_id task.expense.id %}">{{ task.estimated_expense_amount|floatformat:'2g' }}</a>
          {% else %}
            <i class="fa-solid fa-dollar-sign fa-sm"></i>
            {{ task.estimated_expense_amount|floatformat:'2g' }}
          {% endif %}
          {% include 'partials/td_approvement_part.html' with approvement=task.expense.approvement %}
        </p>
        <p class="card-text">
          <i class="fa-regular fa-circle-check"></i>
          {{ progress.task_states_count }}/{{ progress.task_process_states_count }}
          {% include 'partials/task_status.html' %}
        </p>
        {{task.date_created}}
        <p class="card-text"></p>
      </div>
    </div>
  </div>
</div>

charity/projects/templates/partials/project_tasks_card.html
<div class="card mb-4">
  <div class="card-header">
    {{items_count}} <i class="fa-solid fa-list-check"></i>
    Tasks
  </div>
  <div class="card-body">
    <div class="row">
      <div class="col">
        <div class="bg bg-secondary rounded text-light text-center">TODO</div>
      </div>
      <div class="col">
        <div class="bg bg-primary rounded text-light text-center">In Progress</div>
      </div>
      <div class="col">
        <div class="bg bg-info rounded text-dark text-center">On Review</div>
      </div>
      <div class="col">
        <div class="bg bg-success rounded text-light text-center">Done</div>
      </div>
    </div>

    <div class="row">
      <div class="col">
        {{ todo_tasks }}
      </div>
      <div class="col">
        {{ in_progress_tasks }}
      </div>
      <div class="col">
        {{ on_review_tasks }}
      </div>
      <div class="col">
        {{ done_tasts }}
      </div>
    </div>

    <div class="row mt-2">
      <div>
        {% include 'paginator.html' with obj_page=page %}
      </div>
    </div>
  </div>
</div>

charity/projects/templates/partials/project_tasks_list.html
{% load projectstags %}
{% load projectfilters %}
<div>
  <a {% if project|validate_pre_requirements:user %}
      href="{% url 'tasks:create'%}?project_id={{ project.id }}" 
      class="btn btn-link"
     {% else %}
       href=""  class="btn btn-link disabled"
     {% endif %}>Add task</a>
</div>
{% render_tasks_board project=project tasks=page%}

charity/projects/templates/partials/project_wards_list.html
{% load customtags %}
{% load projectfilters %}
<div>
  <a  {% if project|validate_pre_requirements:user %}
        href="{% url 'projects:add_ward_to_project' project.id %}" 
        class="btn btn-link"
      {% else %}
        href=""  class="btn btn-link disabled"
      {% endif %}>Add ward</a>
</div>
<div class="card mb-4">
  <div class="card-header">
    {{items_count}} <i class="fa-solid fa-leaf"></i>
    Wards
  </div>
  <div class="card-body">
    <table class="table table-striped">
      <tbody>
        {% for ward in page %}
          <tr>
            <td>
              <div>
                <h6>
                  {{ ward|thumbnail:50 }}
                  <a href="{% url 'wards:get_details' ward.id %}">{{ ward.name }}</a>
                </h6>
                {{ ward.date_created }}
              {% if ward.is_inactive %}
                <span class="badge bg-secondary">inactive</span>
              {% elif ward.project_tasks_exists %}
                <span class="badge bg-primary">in work</span>
              {% else %}
                <span class="badge bg-primary">active</span>
              {% endif %}
              </div>
                {% if ward.task.id %}
                  <a href="{% url 'tasks:get_details' ward.task.id %}">{{ ward.task.name }}</a>
                {% endif %}
            </td>
            <td class="align-middle">
              <a {% if project|validate_pre_requirements:user and ward|ward_should_not_be_used_by_any_tasks:project %}
                   href="{% url 'projects:remove_project_ward' project.id ward.id%}"
                   class="post-request"
                 {% else %}
                   href="" class="link-disabled"
                 {% endif %}>Remove</a>
           </td>           
          </tr>
        {% endfor %}
      </tbody>
    </table>
    {% include 'paginator.html' with obj_page=page %}
  </div>
  {% include 'generic_errormodal.html' %}
  {% include 'partials/js.html' %}